### ISSUE TITLE
Vue 3

### ISSUE THREAD

**Issue by diachedelic** [posva/vue-reactive-refs#234]
Using @vue/compat, the [beforeCreate hook in proxy.ts](https://github.com/posva/vue-reactive-refs/blob/adc86c9e7c0f774b20245d9da7ed2bb94a796fe4/src/proxy.ts#L10) throws an exception:
```
this.$refs = new Proxy(...)
TypeError: 'set' on proxy: trap returned falsish for property
```
My Vue 3 fix is to change the hook to this:
```
beforeCreate() {
    this.$.refs = reactive({});
}
```
Note the period between the '$' and the 'refs'.

I swore I read somewhere that $refs was going to be reactive in Vue 3, but it seems not to be. Maybe I just  imagined it...

**Comment by IceBlizz6** [comment]
Hey @diachedelic 
Would you be able to create a complete Vue 3 migration guide or just a pull request with the changes?
We are currently using this dependency and we need Vue 3 support.
I don't know anything about the developers on this project or anything, but would be helpful for those of us who still rely on this project.

**Comment by diachedelic** [comment]
It is so easy to get reactive refs in Vue 3 that a plugin isn't really justified. I recommend that you simple include the following `beforeCreate` hook in any component which depends on reactive refs:

```
import {reactive} from "vue";
export default {
    beforeCreate() {
        this.$.refs = reactive({});
    }
};
```

If you want reactive refs in every component automatically, add the hook globally:

```
import {createApp, reactive} from "vue";
const app = createApp(...);
app.mixin({
    beforeCreate() {
        this.$.refs = reactive({});
    }
});
```

**Comment by IceBlizz6** [comment]
@diachedelic 
Thank you very much!
We added it globally.

**Comment by qbunia** [comment]
> It is so easy to get reactive refs in Vue 3 that a plugin isn't really justified. I recommend that you simply include the following `beforeCreate` hook in any component which depends on reactive refs:
> 
> ```
> import {reactive} from "vue";
> export default {
>     beforeCreate() {
>         this.$.refs = reactive({});
>     }
> };
> ```
> 
> If you want reactive refs in every component automatically, add the hook globally:
> 
> ```
> import {createApp, reactive} from "vue";
> const app = createApp(...);
> app.mixin({
>     beforeCreate() {
>         this.$.refs = reactive({});
>     }
> });
> ```

It doesnt work with vue 3.2.33

**Comment by diachedelic** [comment]
Can it be fixed?

**Comment by diachedelic** [comment]
My preferred solution these days is to pass a function to the `ref` attribute, assigning the element to a data property:

```
<img :ref="(element) => my_button = element" />
```

Then there is no need to mess with `$refs`.
